exports.token = "";
exports.couch_user = "";
exports.couch_pass = "";
exports.database = ""; //beta or live
exports.default_prefix = "";
exports.eval_users = [ "IDs are strings" ];
exports.say_users = [ "IDs are strings" ];
exports.weebsh = "";
exports.vote_lock = false;
exports.guild_update_webhook = "";
exports.dbl_token = "";